include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    use_super_parameters: true

analyzer:
  errors:
    invalid_annotation_target: ignore
